FROM amazoncorretto:21
ARG SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
ENV ARTIFACT_NAME=zenix.jar
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME
COPY build/libs/$ARTIFACT_NAME .

EXPOSE 8080
ENTRYPOINT java -server -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dapplication_name=Zenix -jar $ARTIFACT_NAME

